backend:
    name: github
    repo: VincentPFG/neo10

media_folder: static/uploads
public_folder: /uploads

collections:
    -
        name: posts
        label: Posts
        folder: blog
        create: true
        fields: 
            -
                label: Titre
                name: title
                widget: string
            -
                label: Publish Date
                name: date
                widget: date
            -
                label: Body
                name: body
                widget: markdown
    -
        name: person
        label: Personne
        folder: person
        create: true
        fields:
            -
                name: name
                label: Nom
                widget: string
            -
                name: age
                label: Age
                widget: number
                valueType: int
                min: 0